import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import GithubIcon from '../icons/github';
import GoogleIcon from '../icons/google';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
	const { data: session } = useSession();
	const [secretMessage, setSecretMessage] = useState<string | null>(null);
	const { data, error, isLoading } = trpc.useQuery(['auth.getSecretMessage']);
	useEffect(() => {
		setSecretMessage(data ?? '');
	}, [data]);

	return (
		<>
			<Head>
				<title>Binge</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
					Binge.<span className="text-purple-400">app</span>
				</h1>
				{session ? (
					<div className="flex-col pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
						<p>Hello {session.user ? session.user.name : 'Loading...'}</p>
						<div className="p-2"></div>
						<button
							className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
							onClick={() => signOut()}
						>
							Sign Out
						</button>
						<div className="absolute bottom-6 text-2xl text-purple-400">
							{secretMessage}
						</div>
					</div>
				) : (
					<>
						<div className="m-4">Not Signed In.</div>
						<button
							className="flex text-white bg-black hover:bg-purple-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none "
							onClick={() => signIn('google')}
						>
							<GoogleIcon height={24} width={24} />
							<span className="pl-2">Sign In With Google</span>
						</button>
						<button
							className="flex text-white bg-black hover:bg-purple-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none"
							onClick={() => signIn('github')}
						>
							<GithubIcon height={24} width={24} />
							<span className="pl-2">Sign In With Github</span>
						</button>
					</>
				)}
			</main>
		</>
	);
};

export default Home;
